#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 [app id]"
  exit 1
fi

APP_ID=$1

if [ "$(git branch --list ${APP_ID})" ]; then
  git checkout ${APP_ID}
else
  git checkout -b ${APP_ID}
fi

echo "Syncing ${APP_ID} with origin/${APP_ID} if it exists..."
git reset --hard origin/${APP_ID} || true
